openapi: 3.0.1
servers:
  - url: https://api.hubapi.com/
info:
  title: Domains
  version: v3
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_developers.hubspot.com_hubfs_assets_hubspot.com_buzz_HubSpotOpenGraph.png
  x-origin:
    - format: openapi
      url: https://api.hubspot.com/api-catalog-public/v1/apis/cms/v3/domains
      version: "3.0"
  x-providerName: hubapi.com
  x-serviceName: cms
tags:
  - description: Operations for fetching domains
    name: Domains
paths:
  /cms/v3/domains/:
    get:
      description: Returns all existing domains that have been created. Results can be limited and filtered by creation or updated date.
      operationId: get-/cms/v3/domains/_getPage
      parameters:
        - description: Only return domains created at this date.
          explode: true
          in: query
          name: createdAt
          required: false
          schema:
            format: int64
            type: integer
          style: form
        - description: Only return domains created after this date.
          explode: true
          in: query
          name: createdAfter
          required: false
          schema:
            format: int64
            type: integer
          style: form
        - description: Only return domains created before this date.
          explode: true
          in: query
          name: createdBefore
          required: false
          schema:
            format: int64
            type: integer
          style: form
        - description: Only return domains updated at this date.
          explode: true
          in: query
          name: updatedAt
          required: false
          schema:
            format: int64
            type: integer
          style: form
        - description: Only return domains updated after this date.
          explode: true
          in: query
          name: updatedAfter
          required: false
          schema:
            format: int64
            type: integer
          style: form
        - description: Only return domains updated before this date.
          explode: true
          in: query
          name: updatedBefore
          required: false
          schema:
            format: int64
            type: integer
          style: form
        - explode: true
          in: query
          name: sort
          required: false
          schema:
            items:
              type: string
            type: array
          style: form
        - explode: true
          in: query
          name: properties
          required: false
          schema:
            items:
              type: string
            type: array
          style: form
        - description: The paging cursor token of the last successfully read resource will be returned as the `paging.next.after` JSON property of a paged response containing more results.
          explode: true
          in: query
          name: after
          required: false
          schema:
            type: string
          style: form
        - explode: true
          in: query
          name: before
          required: false
          schema:
            type: string
          style: form
        - description: Maximum number of results per page.
          explode: true
          in: query
          name: limit
          required: false
          schema:
            format: int32
            type: integer
          style: form
        - description: Whether to return only results that have been archived.
          explode: true
          in: query
          name: archived
          required: false
          schema:
            type: boolean
          style: form
      responses:
        "200":
          content:
            application/json:
              example:
                results:
                  - createdAt: 2017-07-24T17:24:09.141Z
                    domain: 234.hs-sites.com
                    expectedCname: 234.group34.sites.hubspot.net
                    id: "1234"
                    isHttpsEnabled: true
                    isHttpsOnly: false
                    isManuallyMarkedAsResolving: false
                    isPrimaryBlogPost: true
                    isPrimaryEmail: false
                    isPrimaryKnowledge: false
                    isPrimaryLandingPage: false
                    isPrimarySitePage: false
                    isResolving: true
                    isUsedForBlogPost: true
                    isUsedForEmail: false
                    isUsedForKnowledge: false
                    isUsedForLandingPage: false
                    isUsedForSitePage: false
                    redirectTo: ""
                    updatedAt: 2017-07-25T18:20:00.000Z
                  - createdAt: 2017-07-11T13:00:52.928Z
                    domain: test.demo.com
                    expectedCname: 234.group34.sites.hubspot.net
                    id: "4321"
                    isHttpsEnabled: true
                    isHttpsOnly: false
                    isManuallyMarkedAsResolving: false
                    isPrimaryBlogPost: true
                    isPrimaryEmail: false
                    isPrimaryKnowledge: false
                    isPrimaryLandingPage: false
                    isPrimarySitePage: false
                    isResolving: true
                    isUsedForBlogPost: true
                    isUsedForEmail: false
                    isUsedForKnowledge: false
                    isUsedForLandingPage: false
                    isUsedForSitePage: false
                    redirectTo: ""
                    updatedAt: 2019-10-08T16:54:57.165Z
                total: 2
              schema:
                $ref: "#/components/schemas/CollectionResponseWithTotalDomain"
          description: successful operation
        default:
          $ref: "#/components/responses/Error"
      security:
        - hapikey: []
      summary: Get current domains
      tags:
        - Domains
  "/cms/v3/domains/{domainId}":
    get:
      description: Returns a single domains with the id specified.
      operationId: get-/cms/v3/domains/{domainId}_getById
      parameters:
        - description: The unique ID of the domain.
          explode: false
          in: path
          name: domainId
          required: true
          schema:
            type: string
          style: simple
        - description: Whether to return only results that have been archived.
          explode: true
          in: query
          name: archived
          required: false
          schema:
            type: boolean
          style: form
      responses:
        "200":
          content:
            application/json:
              example:
                createdAt: 2017-07-11T13:00:52.928Z
                domain: 99558489.hubspot.com
                expectedCname: 99558489.group39.sites.hubspotqa.net
                id: "3210329704"
                isHttpsEnabled: true
                isHttpsOnly: false
                isManuallyMarkedAsResolving: false
                isPrimaryBlogPost: true
                isPrimaryEmail: false
                isPrimaryKnowledge: false
                isPrimaryLandingPage: false
                isPrimarySitePage: false
                isResolving: true
                isUsedForBlogPost: true
                isUsedForEmail: false
                isUsedForKnowledge: false
                isUsedForLandingPage: false
                isUsedForSitePage: false
                redirectTo: ""
                updatedAt: 2019-10-08T16:54:57.165Z
              schema:
                $ref: "#/components/schemas/Domain"
          description: successful operation
        default:
          $ref: "#/components/responses/Error"
      security:
        - hapikey: []
      summary: Get a single domain
      tags:
        - Domains
components:
  responses:
    Error:
      content:
        "*/*":
          schema:
            $ref: "#/components/schemas/Error"
      description: An error occurred.
  schemas:
    CollectionResponseWithTotalDomain:
      properties:
        paging:
          $ref: "#/components/schemas/Paging"
        results:
          items:
            $ref: "#/components/schemas/Domain"
          type: array
        total:
          format: int32
          type: integer
      required:
        - results
        - total
      type: object
    Domain:
      properties:
        actualCname:
          type: string
        actualIp:
          type: string
        apexDomain:
          type: string
        apexIpAddresses:
          items:
            type: string
          type: array
        apexResolutionStatus:
          enum:
            - INELIGIBLE
            - SUGGEST_RESOLVING
            - ALREADY_RESOLVING
            - ERROR
          type: string
        authorAt:
          format: int64
          type: integer
        brandId:
          format: int64
          type: integer
        cdnPurgeEmbargoTime:
          format: int64
          type: integer
        certificateId:
          format: int64
          type: integer
        consecutiveNonResolvingCount:
          format: int32
          type: integer
        correctCname:
          type: string
        cosObjectType:
          enum:
            - CONTENT
            - EXTENSION_RESOURCE
            - LAYOUT
            - CUSTOM_WIDGET
            - WIDGET
            - FORM
            - PLACEMENT
            - IMAGE
            - DOMAIN_SETTINGS
            - SITE_SETTINGS
            - EMAIL_ADDRESS
            - WORKFLOW
            - HUBDB_TABLE
            - REDIRECT_URL
            - DESIGN_FOLDER
            - SITE_MAP
            - DOMAIN
            - BLOG
            - FILE
            - FOLDER
            - SITE_MENU
            - THEME
            - CONTENT_GROUP
            - FOLLOW_ME
            - KNOWLEDGE_BASE
            - LIST_MEMBERSHIP
            - CONTACT_MEMBERSHIP
            - PASSWORD_PROTECTED
            - UNRESTRICTED_ACCESS
            - MARKETPLACE_LISTING
            - LAYOUT_SECTION
            - THEME_SETTINGS
            - VIDEO_PLAYER
            - URL_MAPPING
            - KNOWLEDGE_CATEGORY
            - KNOWLEDGE_HOMEPAGE_CATEGORY
            - RAW_ASSET
            - GLOBAL_CONTENT
            - HUBDB_TABLE_ROW
            - BLOG_AUTHOR
            - SERVERLESS_FUNCTION
            - KNOWLEDGE_CATEGORY_TRANSLATION
          type: string
        created:
          format: int64
          type: integer
        createdById:
          format: int32
          type: integer
        deletable:
          type: boolean
        derivedBrandName:
          type: string
        domain:
          type: string
        domainCdnConfig:
          $ref: "#/components/schemas/DomainCdnConfig"
        fullCategoryKey:
          type: string
        id:
          format: int64
          type: integer
        isAnyPrimary:
          type: boolean
        isDnsCorrect:
          type: boolean
        isInternalDomain:
          type: boolean
        isLegacy:
          type: boolean
        isLegacyDomain:
          type: boolean
        isResolving:
          type: boolean
        isResolvingIgnoringManuallyMarkedAsResolving:
          type: boolean
        isResolvingInternalProperty:
          type: boolean
        isSetupComplete:
          type: boolean
        isSslEnabled:
          type: boolean
        isSslOnly:
          type: boolean
        isStagingDomain:
          type: boolean
        isUsedForAnyContentType:
          type: boolean
        isUsedForBlogPost:
          type: boolean
        isUsedForEmail:
          type: boolean
        isUsedForKnowledge:
          type: boolean
        isUsedForLandingPage:
          type: boolean
        isUsedForSitePage:
          type: boolean
        label:
          type: string
        manuallyMarkedAsResolving:
          type: boolean
        portalId:
          format: int32
          type: integer
        primaryBlog:
          type: boolean
        primaryBlogPost:
          type: boolean
        primaryClickTracking:
          type: boolean
        primaryEmail:
          type: boolean
        primaryKnowledge:
          type: boolean
        primaryLandingPage:
          type: boolean
        primaryLegacyPage:
          type: boolean
        primarySitePage:
          type: boolean
        publicSuffix:
          type: string
        secondaryToDomain:
          type: string
        setUpLanguage:
          type: string
        setupInfo:
          $ref: "#/components/schemas/DomainSetupInfo"
        setupTaskId:
          format: int64
          type: integer
        siteId:
          format: int64
          type: integer
        sslCname:
          type: string
        sslRequestId:
          format: int64
          type: integer
        teamIds:
          items:
            format: int64
            type: integer
          type: array
        updated:
          format: int64
          type: integer
        updatedById:
          format: int32
          type: integer
      required:
        - actualCname
        - actualIp
        - apexDomain
        - apexIpAddresses
        - apexResolutionStatus
        - authorAt
        - brandId
        - cdnPurgeEmbargoTime
        - certificateId
        - consecutiveNonResolvingCount
        - correctCname
        - cosObjectType
        - created
        - createdById
        - deletable
        - derivedBrandName
        - domain
        - domainCdnConfig
        - fullCategoryKey
        - id
        - isAnyPrimary
        - isDnsCorrect
        - isInternalDomain
        - isLegacy
        - isLegacyDomain
        - isResolving
        - isResolvingIgnoringManuallyMarkedAsResolving
        - isResolvingInternalProperty
        - isSetupComplete
        - isSslEnabled
        - isSslOnly
        - isStagingDomain
        - isUsedForAnyContentType
        - isUsedForBlogPost
        - isUsedForEmail
        - isUsedForKnowledge
        - isUsedForLandingPage
        - isUsedForSitePage
        - label
        - manuallyMarkedAsResolving
        - portalId
        - primaryBlog
        - primaryBlogPost
        - primaryClickTracking
        - primaryEmail
        - primaryKnowledge
        - primaryLandingPage
        - primaryLegacyPage
        - primarySitePage
        - publicSuffix
        - secondaryToDomain
        - setUpLanguage
        - setupInfo
        - setupTaskId
        - siteId
        - sslCname
        - sslRequestId
        - teamIds
        - updated
        - updatedById
      type: object
    DomainCdnConfig:
      properties:
        alternateOriginHostname:
          type: string
        cdnGroupId:
          type: string
        cdnId:
          type: string
        certExpirationDate:
          format: int64
          type: integer
        certId:
          format: int64
          type: integer
        cname:
          type: string
        cnameTarget:
          type: string
        created:
          format: int64
          type: integer
        domainId:
          format: int64
          type: integer
        httpBody:
          type: string
        httpUrlPath:
          type: string
        id:
          format: int64
          type: integer
        minimumTlsVersion:
          enum:
            - "1.0"
            - "1.1"
            - "1.2"
            - "1.3"
            - none
            - "null"
          type: string
        portalId:
          format: int32
          type: integer
        sslStatus:
          enum:
            - "0"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
            - "9"
            - "10"
            - "11"
          type: string
        updated:
          format: int64
          type: integer
        validationMethod:
          enum:
            - "0"
            - "1"
            - "2"
          type: string
      required:
        - alternateOriginHostname
        - cdnGroupId
        - cdnId
        - certExpirationDate
        - certId
        - cname
        - cnameTarget
        - created
        - domainId
        - httpBody
        - httpUrlPath
        - id
        - minimumTlsVersion
        - portalId
        - sslStatus
        - updated
        - validationMethod
      type: object
    DomainSetupInfo:
      properties:
        supportsSslExternally:
          type: boolean
        whoIsEmailAddresses:
          items:
            type: string
          type: array
      required:
        - supportsSslExternally
        - whoIsEmailAddresses
      type: object
    Error:
      example:
        category: VALIDATION_ERROR
        correlationId: aeb5f871-7f07-4993-9211-075dc63e7cbf
        links:
          knowledge-base: https://www.hubspot.com/products/service/knowledge-base
        message: Invalid input (details will vary based on the error)
      properties:
        category:
          description: The error category
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            invalidPropertyName:
              - propertyValue
            missingScopes:
              - scope1
              - scope2
          type: object
        correlationId:
          description: A unique identifier for the request. Include this value with any error reports or support tickets
          example: aeb5f871-7f07-4993-9211-075dc63e7cbf
          format: uuid
          type: string
        errors:
          description: further information about the error
          items:
            $ref: "#/components/schemas/ErrorDetail"
          type: array
        links:
          additionalProperties:
            type: string
          description: A map of link names to associated URIs containing documentation about the error or recommended remediation steps
          type: object
        message:
          description: A human readable message describing the error along with remediation steps where appropriate
          example: An error occurred
          type: string
        subCategory:
          description: A specific category that contains more specific detail about the error
          type: string
      required:
        - category
        - correlationId
        - message
      type: object
    ErrorDetail:
      properties:
        code:
          description: The status code associated with the error detail
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
              - scope1
              - scope2
          type: object
        in:
          description: The name of the field or parameter in which the error was found.
          type: string
        message:
          description: A human readable message describing the error along with remediation steps where appropriate
          type: string
        subCategory:
          description: A specific category that contains more specific detail about the error
          type: string
      required:
        - message
      type: object
    NextPage:
      properties:
        after:
          type: string
        link:
          type: string
      required:
        - after
      type: object
    Paging:
      properties:
        next:
          $ref: "#/components/schemas/NextPage"
      type: object
  securitySchemes:
    hapikey:
      in: query
      name: hapikey
      type: apiKey
x-hubspot-available-client-libraries:
  - PHP
  - Node
  - Python
  - Ruby
